extends Node

signal INVENTORY_OPENED
signal INVENTORY_CLOSED
signal INVENTORY_ITEM_SELECTED
signal INVENTORY_ITEM_PLACED

# MENU value changes
signal MENU_MAX_SPEED_CHANGED
signal MENU_ACCELERATION_CHANGED
